// Sample data for grocery products and store prices
export const SAMPLE_PRODUCTS = [
  {
    id: 1,
    name: 'Organic Bananas',
    image: 'https://via.placeholder.com/96',
    category: 'Produce',
    storePrices: [
      { rank: 1, storeName: 'Walmart', price: '$0.99/lb', storeImage: 'https://via.placeholder.com/40', isBestDeal: true },
      { rank: 2, storeName: 'Target', price: '$1.29/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 3, storeName: 'Whole Foods', price: '$1.49/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 4, storeName: 'Kroger', price: '$1.59/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 5, storeName: 'Safeway', price: '$1.69/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 6, storeName: 'King Soopers', price: '$1.79/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 7, storeName: 'Amazon Fresh', price: '$1.89/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 8, storeName: 'Costco', price: '$1.99/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 9, storeName: 'Food Lion', price: '$2.09/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 10, storeName: "Trader Joe's", price: '$2.19/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 11, storeName: 'Aldi', price: '$2.29/lb', storeImage: 'https://via.placeholder.com/40' },
    ],
  },
  {
    id: 2,
    name: 'Organic Whole Milk',
    image: 'https://via.placeholder.com/96',
    category: 'Dairy',
    storePrices: [
      { rank: 1, storeName: 'Target', price: '$3.99/gal', storeImage: 'https://via.placeholder.com/40', isBestDeal: true },
      { rank: 2, storeName: 'Walmart', price: '$4.29/gal', storeImage: 'https://via.placeholder.com/40' },
      { rank: 3, storeName: 'Whole Foods', price: '$4.49/gal', storeImage: 'https://via.placeholder.com/40' },
      { rank: 4, storeName: 'Kroger', price: '$4.69/gal', storeImage: 'https://via.placeholder.com/40' },
      { rank: 5, storeName: 'Safeway', price: '$4.89/gal', storeImage: 'https://via.placeholder.com/40' },
      { rank: 6, storeName: 'King Soopers', price: '$4.99/gal', storeImage: 'https://via.placeholder.com/40' },
      { rank: 7, storeName: 'Amazon Fresh', price: '$5.19/gal', storeImage: 'https://via.placeholder.com/40' },
      { rank: 8, storeName: 'Costco', price: '$5.29/gal', storeImage: 'https://via.placeholder.com/40' },
      { rank: 9, storeName: 'Food Lion', price: '$5.49/gal', storeImage: 'https://via.placeholder.com/40' },
      { rank: 10, storeName: "Trader Joe's", price: '$5.69/gal', storeImage: 'https://via.placeholder.com/40' },
      { rank: 11, storeName: 'Aldi', price: '$5.89/gal', storeImage: 'https://via.placeholder.com/40' },
    ],
  },
  {
    id: 3,
    name: 'Free Range Eggs (Dozen)',
    image: 'https://via.placeholder.com/96',
    category: 'Dairy',
    storePrices: [
      { rank: 1, storeName: 'Aldi', price: '$2.99', storeImage: 'https://via.placeholder.com/40', isBestDeal: true },
      { rank: 2, storeName: 'Walmart', price: '$3.49', storeImage: 'https://via.placeholder.com/40' },
      { rank: 3, storeName: 'Target', price: '$3.99', storeImage: 'https://via.placeholder.com/40' },
      { rank: 4, storeName: 'Kroger', price: '$4.29', storeImage: 'https://via.placeholder.com/40' },
      { rank: 5, storeName: 'Safeway', price: '$4.49', storeImage: 'https://via.placeholder.com/40' },
      { rank: 6, storeName: 'Food Lion', price: '$4.69', storeImage: 'https://via.placeholder.com/40' },
      { rank: 7, storeName: 'King Soopers', price: '$4.89', storeImage: 'https://via.placeholder.com/40' },
      { rank: 8, storeName: 'Amazon Fresh', price: '$4.99', storeImage: 'https://via.placeholder.com/40' },
      { rank: 9, storeName: 'Costco', price: '$5.29', storeImage: 'https://via.placeholder.com/40' },
      { rank: 10, storeName: "Trader Joe's", price: '$5.49', storeImage: 'https://via.placeholder.com/40' },
      { rank: 11, storeName: 'Whole Foods', price: '$5.99', storeImage: 'https://via.placeholder.com/40' },
    ],
  },
  {
    id: 4,
    name: 'Organic Baby Spinach (16oz)',
    image: 'https://via.placeholder.com/96',
    category: 'Produce',
    storePrices: [
      { rank: 1, storeName: 'Costco', price: '$3.49', storeImage: 'https://via.placeholder.com/40', isBestDeal: true },
      { rank: 2, storeName: 'Walmart', price: '$3.99', storeImage: 'https://via.placeholder.com/40' },
      { rank: 3, storeName: 'Target', price: '$4.29', storeImage: 'https://via.placeholder.com/40' },
      { rank: 4, storeName: 'Aldi', price: '$4.49', storeImage: 'https://via.placeholder.com/40' },
      { rank: 5, storeName: 'Kroger', price: '$4.69', storeImage: 'https://via.placeholder.com/40' },
      { rank: 6, storeName: 'Safeway', price: '$4.89', storeImage: 'https://via.placeholder.com/40' },
      { rank: 7, storeName: 'Food Lion', price: '$4.99', storeImage: 'https://via.placeholder.com/40' },
      { rank: 8, storeName: 'King Soopers', price: '$5.19', storeImage: 'https://via.placeholder.com/40' },
      { rank: 9, storeName: 'Amazon Fresh', price: '$5.29', storeImage: 'https://via.placeholder.com/40' },
      { rank: 10, storeName: "Trader Joe's", price: '$5.49', storeImage: 'https://via.placeholder.com/40' },
      { rank: 11, storeName: 'Whole Foods', price: '$5.99', storeImage: 'https://via.placeholder.com/40' },
    ],
  },
  {
    id: 5,
    name: 'Organic Ground Beef (1lb)',
    image: 'https://via.placeholder.com/96',
    category: 'Meat',
    storePrices: [
      { rank: 1, storeName: 'Walmart', price: '$5.99/lb', storeImage: 'https://via.placeholder.com/40', isBestDeal: true },
      { rank: 2, storeName: 'Aldi', price: '$6.49/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 3, storeName: 'Target', price: '$6.99/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 4, storeName: 'Kroger', price: '$7.29/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 5, storeName: 'Costco', price: '$7.49/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 6, storeName: 'Safeway', price: '$7.69/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 7, storeName: 'Food Lion', price: '$7.89/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 8, storeName: 'King Soopers', price: '$7.99/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 9, storeName: 'Amazon Fresh', price: '$8.29/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 10, storeName: "Trader Joe's", price: '$8.49/lb', storeImage: 'https://via.placeholder.com/40' },
      { rank: 11, storeName: 'Whole Foods', price: '$8.99/lb', storeImage: 'https://via.placeholder.com/40' },
    ],
  },
  {
    id: 6,
    name: 'Organic Quinoa (16oz)',
    image: 'https://via.placeholder.com/96',
    category: 'Grains',
    storePrices: [
      { rank: 1, storeName: "Trader Joe's", price: '$4.99', storeImage: 'https://via.placeholder.com/40', isBestDeal: true },
      { rank: 2, storeName: 'Aldi', price: '$5.29', storeImage: 'https://via.placeholder.com/40' },
      { rank: 3, storeName: 'Costco', price: '$5.49', storeImage: 'https://via.placeholder.com/40' },
      { rank: 4, storeName: 'Walmart', price: '$5.79', storeImage: 'https://via.placeholder.com/40' },
      { rank: 5, storeName: 'Target', price: '$5.99', storeImage: 'https://via.placeholder.com/40' },
      { rank: 6, storeName: 'Kroger', price: '$6.29', storeImage: 'https://via.placeholder.com/40' },
      { rank: 7, storeName: 'Safeway', price: '$6.49', storeImage: 'https://via.placeholder.com/40' },
      { rank: 8, storeName: 'Food Lion', price: '$6.69', storeImage: 'https://via.placeholder.com/40' },
      { rank: 9, storeName: 'King Soopers', price: '$6.89', storeImage: 'https://via.placeholder.com/40' },
      { rank: 10, storeName: 'Amazon Fresh', price: '$6.99', storeImage: 'https://via.placeholder.com/40' },
      { rank: 11, storeName: 'Whole Foods', price: '$7.49', storeImage: 'https://via.placeholder.com/40' },
    ],
  },
];
