/**
 * Category Data Constants
 * All 39 categories from PriceLens Figma
 */

import { Category } from '@/types';

export const CATEGORIES: Record<string, Category> = {
  search: {
    id: 'search',
    name: 'Search',
    slug: 'search',
    description: 'Search across all categories and stores',
    icon: 'search',
    iconColor: '#3B82F6',
    type: 'product',
    stores: [],
    isNew: false,
  },
  
  allretailers: {
    id: 'allretailers',
    name: 'All Retailers',
    slug: 'all-retailers',
    description: 'Search across Amazon, Walmart, Target, Best Buy, and more',
    icon: 'storefront',
    iconColor: '#10B981',
    type: 'product',
    stores: [],
    isNew: true,
  },
  
  groceries: {
    id: 'groceries',
    name: 'Groceries',
    slug: 'groceries',
    description: 'Compare grocery prices across 11 major stores',
    icon: 'cart',
    iconColor: '#10B981',
    type: 'product',
    stores: ['walmart', 'target', 'wholefoods', 'kroger', 'safeway', 'kingsoopers', 'amazonfresh', 'costco', 'foodlion', 'traderjoes', 'aldi'],
    subcategories: [
      { id: 'produce', name: 'Produce' },
      { id: 'dairy', name: 'Dairy' },
      { id: 'meat', name: 'Meat & Seafood' },
      { id: 'bakery', name: 'Bakery' },
      { id: 'pantry', name: 'Pantry' },
    ],
  },
  
  electronics: {
    id: 'electronics',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Find the best deals on tech and gadgets',
    icon: 'laptop',
    iconColor: '#3B82F6',
    type: 'product',
    stores: ['amazon', 'bestbuy', 'walmart', 'target', 'newegg', 'bhphoto', 'costco', 'microcenter', 'samsclub'],
    subcategories: [
      { id: 'tvs', name: 'TVs', count: 31 },
      { id: 'headphones', name: 'Headphones', count: 12 },
      { id: 'gaming', name: 'Gaming', count: 30 },
      { id: 'tablets', name: 'Tablets', count: 17 },
      { id: 'accessories', name: 'Accessories', count: 6 },
    ],
  },
  
  kitchen: {
    id: 'kitchen',
    name: 'Kitchen & Appliances',
    slug: 'kitchen',
    description: 'Compare kitchen appliances and cookware prices',
    icon: 'utensils',
    iconColor: '#F97316',
    type: 'product',
    stores: ['amazon', 'walmart', 'target', 'costco'],
  },
  
  homeaccessories: {
    id: 'homeaccessories',
    name: 'Home Accessories & Decor',
    slug: 'home-accessories',
    description: 'Find the best home accessories, decor, and accent pieces',
    icon: 'sparkles',
    iconColor: '#06B6D4',
    type: 'product',
    stores: ['amazon', 'walmart', 'target'],
  },
  
  clothing: {
    id: 'clothing',
    name: 'Clothing',
    slug: 'clothing',
    description: 'Compare fashion prices across retailers',
    icon: 'shirt',
    iconColor: '#8B5CF6',
    type: 'product',
    stores: ['amazon', 'walmart', 'target'],
  },
  
  footwear: {
    id: 'footwear',
    name: 'Footwear',
    slug: 'footwear',
    description: 'Compare shoe prices from top brands',
    icon: 'shoe',
    iconColor: '#3B82F6',
    type: 'product',
    stores: ['amazon', 'walmart', 'target'],
  },
  
  books: {
    id: 'books',
    name: 'Books',
    slug: 'books',
    description: 'Find the best book prices online',
    icon: 'book',
    iconColor: '#F97316',
    type: 'product',
    stores: ['amazon', 'walmart', 'target', 'barnesandnoble'],
    subcategories: [
      { id: 'mystery', name: 'Mystery & Thriller' },
      { id: 'fiction', name: 'Fiction' },
      { id: 'non-fiction', name: 'Non-Fiction' },
      { id: 'sci-fi', name: 'Science Fiction' },
      { id: 'romance', name: 'Romance' },
      { id: 'biography', name: 'Biography' },
      { id: 'history', name: 'History' },
      { id: 'self-help', name: 'Self-Help' },
    ],
  },
  
  household: {
    id: 'household',
    name: 'Household Items',
    slug: 'household',
    description: 'Compare prices on home essentials',
    icon: 'home',
    iconColor: '#06B6D4',
    type: 'product',
    stores: ['amazon', 'walmart', 'target', 'costco'],
  },
  
  medicine: {
    id: 'medicine',
    name: 'Medicine & Health',
    slug: 'medicine',
    description: 'Find the best prices on medications',
    icon: 'pill',
    iconColor: '#EF4444',
    type: 'product',
    stores: [],
  },
  
  rentalcars: {
    id: 'rentalcars',
    name: 'Rental Cars',
    slug: 'rental-cars',
    description: 'Compare rental car prices across companies',
    icon: 'car',
    iconColor: '#8B5CF6',
    type: 'service',
    stores: [],
  },
  
  hotels: {
    id: 'hotels',
    name: 'Hotels',
    slug: 'hotels',
    description: 'Find the best hotel deals',
    icon: 'hotel',
    iconColor: '#EC4899',
    type: 'service',
    stores: [],
  },
  
  airfare: {
    id: 'airfare',
    name: 'Airfare',
    slug: 'airfare',
    description: 'Compare flight prices across 10 booking sites',
    icon: 'airplane',
    iconColor: '#06B6D4',
    type: 'service',
    stores: [],
  },
  
  tires: {
    id: 'tires',
    name: 'Tires',
    slug: 'tires',
    description: 'Compare tire prices from top retailers and installers',
    icon: 'car',
    iconColor: '#06B6D4',
    type: 'service',
    stores: [],
  },
  
  haircuts: {
    id: 'haircuts',
    name: 'Haircuts & Salons',
    slug: 'haircuts',
    description: 'Find local salon and barber prices',
    icon: 'scissors',
    iconColor: '#FBBF24',
    type: 'service',
    stores: [],
  },
  
  oilchanges: {
    id: 'oilchanges',
    name: 'Oil Changes',
    slug: 'oil-changes',
    description: 'Compare oil change prices and services',
    icon: 'wrench',
    iconColor: '#F97316',
    type: 'service',
    stores: [],
  },
  
  carwashes: {
    id: 'carwashes',
    name: 'Car Washes',
    slug: 'car-washes',
    description: 'Find the best car wash deals near you',
    icon: 'sparkles',
    iconColor: '#06B6D4',
    type: 'service',
    stores: [],
  },
  
  videogames: {
    id: 'videogames',
    name: 'Video Games',
    slug: 'video-games',
    description: 'Compare game prices across 14 platforms',
    icon: 'gamepad',
    iconColor: '#8B5CF6',
    type: 'product',
    stores: ['amazon', 'walmart', 'target', 'bestbuy'],
  },
  
  gasstations: {
    id: 'gasstations',
    name: 'Gas Stations',
    slug: 'gas-stations',
    description: 'Find the cheapest gas near you',
    icon: 'fuel',
    iconColor: '#FBBF24',
    type: 'service',
    stores: [],
  },
  
  carinsurance: {
    id: 'carinsurance',
    name: 'Car Insurance',
    slug: 'car-insurance',
    description: 'Compare car insurance rates and coverage',
    icon: 'shield',
    iconColor: '#EF4444',
    type: 'service',
    stores: [],
  },
  
  rentersinsurance: {
    id: 'rentersinsurance',
    name: 'Renters Insurance',
    slug: 'renters-insurance',
    description: 'Find the best renters insurance deals',
    icon: 'shield',
    iconColor: '#3B82F6',
    type: 'service',
    stores: [],
  },
  
  apartments: {
    id: 'apartments',
    name: 'Apartments',
    slug: 'apartments',
    description: 'Compare apartment rental prices and amenities',
    icon: 'building',
    iconColor: '#8B5CF6',
    type: 'service',
    stores: [],
  },
  
  services: {
    id: 'services',
    name: 'Services',
    slug: 'services',
    description: 'Compare local service provider prices',
    icon: 'sparkles',
    iconColor: '#EC4899',
    type: 'service',
    stores: [],
  },
  
  fooddelivery: {
    id: 'fooddelivery',
    name: 'Food Delivery',
    slug: 'food-delivery',
    description: 'Compare delivery prices on Uber Eats, DoorDash & more',
    icon: 'utensils',
    iconColor: '#F97316',
    type: 'service',
    stores: [],
  },
  
  massageparlors: {
    id: 'massageparlors',
    name: 'Massage Parlors',
    slug: 'massage',
    description: 'Compare massage services and prices near you',
    icon: 'heart',
    iconColor: '#EC4899',
    type: 'service',
    stores: [],
  },
  
  nailsalons: {
    id: 'nailsalons',
    name: 'Nail Salons',
    slug: 'nail-salons',
    description: 'Find the best nail salon deals in your area',
    icon: 'sparkles',
    iconColor: '#EC4899',
    type: 'service',
    stores: [],
  },
  
  beautyproducts: {
    id: 'beautyproducts',
    name: 'Beauty Products',
    slug: 'beauty',
    description: 'Compare makeup & skincare from Sephora, Ulta & more',
    icon: 'sparkles',
    iconColor: '#EC4899',
    type: 'product',
    stores: [
      'amazon', 'walmart', 'target', 'costco', 
      'ulta', 'sephora', 'cvs', 'walgreens', 
      'riteaid', 'macy', 'nordstrom', 'saks', 
      'sallybeauty', 'beautybrands', 'spacenk', 
      'glossier', 'fenty', 'rarebeauty', 'tarte',
      'benefit', 'clinique', 'estee', 'lancome'
    ],
    backgroundImage: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80', // Beauty/lady theme - user will replace with Pinterest image
  },
  
  gymmemberships: {
    id: 'gymmemberships',
    name: 'Gym Memberships',
    slug: 'gym',
    description: 'Find the best gym membership prices near you',
    icon: 'dumbbell',
    iconColor: '#06B6D4',
    type: 'service',
    stores: [],
  },
  
  sportsequipment: {
    id: 'sportsequipment',
    name: 'Sports Equipment',
    slug: 'sports-equipment',
    description: 'Compare sports and fitness equipment prices',
    icon: 'dumbbell',
    iconColor: '#10B981',
    type: 'product',
    stores: [
      'Dick\'s Sporting Goods',
      'Academy Sports + Outdoors',
      'REI',
      'Nike',
      'Adidas',
      'Under Armour',
      'Foot Locker',
      'Finish Line',
      'Modell\'s Sporting Goods',
      'Big 5 Sporting Goods',
      'Walmart',
      'Target',
      'Amazon',
      'Best Buy',
      'Costco',
      'Sam\'s Club',
      'Scheels',
      'Bass Pro Shops',
      'Cabela\'s',
      'Sports Authority',
      'Champs Sports',
      'Eastbay',
    ],
  },
  
  officesupplies: {
    id: 'officesupplies',
    name: 'Office Supplies',
    slug: 'office',
    description: 'Find the best office supply deals and stationery',
    icon: 'package',
    iconColor: '#6B7280',
    type: 'product',
    stores: [
      'Staples',
      'Office Depot',
      'OfficeMax',
      'Amazon',
      'Walmart',
      'Target',
      'Costco',
      'Sam\'s Club',
      'BJ\'s Wholesale',
      'Quill',
      'Uline',
      'FedEx Office',
      'The Container Store',
      'Best Buy',
      'Newegg',
      'B&H Photo',
      'CDW',
      'Staples Business',
      'Viking Office Products',
      'Shoplet',
      'National Pen',
      'Pen & Gear',
      'Avery',
      'HP',
      'Canon',
    ],
  },
  
  mattresses: {
    id: 'mattresses',
    name: 'Mattresses',
    slug: 'mattresses',
    description: 'Compare mattress prices and brands',
    icon: 'bed',
    iconColor: '#8B5CF6',
    type: 'product',
    stores: [
      'Mattress Firm',
      'Sleep Number',
      'Tempur-Pedic',
      'Casper',
      'Purple',
      'Tuft & Needle',
      'Saatva',
      'Nectar',
      'Leesa',
      'Walmart',
      'Target',
      'Amazon',
      'Costco',
      'Sam\'s Club',
      'BJ\'s Wholesale',
      'Wayfair',
      'Overstock',
      'Home Depot',
      'Lowe\'s',
      'Big Lots',
      'Macy\'s',
      'JCPenney',
      'Kohl\'s',
    ],
  },
  
  furniture: {
    id: 'furniture',
    name: 'Furniture',
    slug: 'furniture',
    description: 'Compare furniture prices across retailers',
    icon: 'sofa',
    iconColor: '#F97316',
    type: 'product',
    stores: ['amazon', 'walmart', 'target', 'wayfair', 'ikea', 'overstock', 'costco'],
  },
  
  
  movingcompanies: {
    id: 'movingcompanies',
    name: 'Moving Companies',
    slug: 'moving',
    description: 'Compare moving company prices and services',
    icon: 'truck',
    iconColor: '#F97316',
    type: 'service',
    stores: [],
  },
  
  storageunits: {
    id: 'storageunits',
    name: 'Storage Units',
    slug: 'storage',
    description: 'Find the best storage unit prices and sizes',
    icon: 'archive',
    iconColor: '#6B7280',
    type: 'service',
    stores: [],
  },
  
  spaservices: {
    id: 'spaservices',
    name: 'Spa Services',
    slug: 'spa',
    description: 'Compare spa services and treatment prices',
    icon: 'sparkles',
    iconColor: '#EC4899',
    type: 'service',
    stores: [],
  },
  
  toolshardware: {
    id: 'toolshardware',
    name: 'Tools & Hardware',
    slug: 'tools',
    description: 'Compare tool and hardware store prices',
    icon: 'wrench',
    iconColor: '#6B7280',
    type: 'product',
    stores: [],
  },
  
  mealkits: {
    id: 'mealkits',
    name: 'Meal Kits',
    slug: 'meal-kits',
    description: 'Compare meal kit delivery service prices',
    icon: 'chef',
    iconColor: '#10B981',
    type: 'service',
    stores: [],
  },
  
  petsupplies: {
    id: 'petsupplies',
    name: 'Pet Supplies',
    slug: 'pet-supplies',
    description: 'Find the best pet supply deals and food',
    icon: 'paw',
    iconColor: '#F97316',
    type: 'product',
    stores: [
      'Petco',
      'PetSmart',
      'Chewy',
      'Amazon',
      'Walmart',
      'Target',
      'Pet Supplies Plus',
      'Pet Valu',
      'Pet Supermarket',
      'Petland',
      'Pet Express',
      'Pet Food Express',
      'Pet Superstore',
      'Pet Depot',
      'Pet Warehouse',
      'Only Natural Pet',
      'PetFlow',
      '1-800-PetMeds',
      'PetMed Express',
      'Costco',
      'Sam\'s Club',
      'BJ\'s Wholesale',
      'Tractor Supply',
      'Farm & Fleet',
    ],
  },
  
  mylist: {
    id: 'mylist',
    name: 'My List',
    slug: 'my-list',
    description: 'Your saved shopping list',
    icon: 'list',
    iconColor: '#3B82F6',
    type: 'product',
    stores: [],
  },
  
  plus: {
    id: 'plus',
    name: 'Plus',
    slug: 'plus',
    description: 'PriceLens Plus features',
    icon: 'trophy',
    iconColor: '#A855F7',
    type: 'product',
    stores: [],
  },
  
  profile: {
    id: 'profile',
    name: 'Profile',
    slug: 'profile',
    description: 'User profile and settings',
    icon: 'person',
    iconColor: '#6B7280',
    type: 'product',
    stores: [],
  },
  
  analytics: {
    id: 'analytics',
    name: 'Analytics',
    slug: 'analytics',
    description: 'Developer analytics dashboard',
    icon: 'bar-chart',
    iconColor: '#10B981',
    type: 'product',
    stores: [],
  },
};

export const CATEGORY_LIST = [
  CATEGORIES.allretailers,
  CATEGORIES.groceries,
  CATEGORIES.electronics,
  CATEGORIES.kitchen,
  CATEGORIES.homeaccessories,
  CATEGORIES.clothing,
  CATEGORIES.footwear,
  CATEGORIES.books,
  CATEGORIES.household,
  CATEGORIES.medicine,
  CATEGORIES.rentalcars,
  CATEGORIES.hotels,
  CATEGORIES.airfare,
  CATEGORIES.tires,
  CATEGORIES.haircuts,
  CATEGORIES.oilchanges,
  CATEGORIES.carwashes,
  CATEGORIES.videogames,
  CATEGORIES.gasstations,
  CATEGORIES.carinsurance,
  CATEGORIES.rentersinsurance,
  CATEGORIES.apartments,
  CATEGORIES.services,
  CATEGORIES.fooddelivery,
  CATEGORIES.massageparlors,
  CATEGORIES.nailsalons,
  CATEGORIES.beautyproducts,
  CATEGORIES.gymmemberships,
  CATEGORIES.sportsequipment,
  CATEGORIES.officesupplies,
  CATEGORIES.mattresses,
  CATEGORIES.furniture,
  CATEGORIES.movingcompanies,
  CATEGORIES.storageunits,
  CATEGORIES.spaservices,
  CATEGORIES.toolshardware,
  CATEGORIES.mealkits,
  CATEGORIES.petsupplies,
];

export const TRENDING_SEARCHES = [
  'iPhone 15',
  'AirPods Pro',
  'Nike Running Shoes',
  'LEGO Sets',
  'Instant Pot',
  'Organic Milk',
];
